#define HAVE_TRANSPORT_USB
#define USB_PRODUCT_ID 0x21e8
#define USB_VENDOR_ID 0x0a5c
#define USE_POSIX_RUN_LOOP
#define REMOTE_DEVICE_DB remote_device_db_memory

#define HAVE_TIME
#define HAVE_MALLOC
#define HAVE_BZERO
#define ENABLE_LOG_INFO 
#define ENABLE_LOG_ERROR

#define HAVE_BLE

#define HCI_ACL_PAYLOAD_SIZE 52

// 

#define MAX_NO_HCI_CONNECTIONS 1
#define MAX_NO_L2CAP_SERVICES  0
#define MAX_NO_L2CAP_CHANNELS  0
#define MAX_NO_RFCOMM_MULTIPLEXERS 0
#define MAX_NO_RFCOMM_SERVICES 0
#define MAX_NO_RFCOMM_CHANNELS 0
#define MAX_NO_DB_MEM_DEVICE_LINK_KEYS  2
#define MAX_NO_DB_MEM_DEVICE_NAMES 0
#define MAX_NO_DB_MEM_SERVICES 0



